apiVersion: v1
kind: Service
metadata:
  labels:
    app: echo-server
  name: echo-server
spec:
  ports:
    - name: echo
      port: 9090
      protocol: TCP
      targetPort: 9090
  selector:
    app: echo-server
  type: ClusterIP